version: '3.1'

services:
  app_student:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_JPA_DATABASE=POSTGRESQL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${PROD_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - "${APP_PORT_PROD}:8080"
    networks:
      - student_app

networks:
  student_app:
    driver: bridge

volumes:
  student_app:
